using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server
{
    /// <summary>
    /// Https certificate type.
    /// </summary>
    public enum HttpsCertificateType
    {
        /// <summary>
        /// Self signed certificate.
        /// </summary>
        [Name("Self Signed", nameof(Shared.Resources.Autogenerated.Resources.HTTPS_CERTIFICATE_TYPE_SELF_SIGNED))]
        SelfSigned = 0,

        /// <summary>
        /// User defined certificate.
        /// </summary>
        [Name("User defined", nameof(Shared.Resources.Autogenerated.Resources.HTTPS_CERTIFICATE_TYPE_USER_DEFINED))]
        UserDefined = 1,
    }
}
