using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    public enum SMTPSecurity
    {
        [Name("None", nameof(Resources.SMTP_SECURITY_NONE_NAME))]
        None = 0,

        [Name("SSL", nameof(Resources.SMTP_SECURITY_SSL_NAME))]
        SSL = 1,
        
        [Name("None", nameof(Resources.SMTP_SECURITY_STARTTLS_NAME))]
        STARTTLS = 2
    }
}
