using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Set for default localized object naming.
    /// </summary>
    public enum DefaultNames
    {
        [Name("Primary", nameof(Resources.BRANCH_DEFAULT_NAME))]
        BRANCH_DEFAULT_NAME,

        [Name("Cash", nameof(Resources.PAYMENT_METHOD_TYPE_CASH_NAME))]
        PAYMENT_METHOD_CASH_NAME,
        
        [Name("Credit Card", nameof(Resources.PAYMENT_METHOD_TYPE_CREDIT_CARD_NAME))]
        PAYMENT_METHOD_CREDIT_CARD_NAME,
        
        [Name("Deposit", nameof(Resources.PAYMENT_METHOD_TYPE_DEPOSIT_NAME))]
        PAYMENT_METHOD_DEPOSIT_NAME,

        [Name("Points", nameof(Resources.PAYMENT_METHOD_TYPE_POINTS_NAME))]
        PAYMENT_METHOD_POINTS_NAME,

        [Name("Endpoints", nameof(Resources.HOST_GROUP_ENDPOINTS_DEFAULT_NAME))]
        HOST_GROUP_ENDPOINTS_DEFAULT_NAME,

        [Name("Computers", nameof(Resources.HOST_GROUP_COMPUERS_DEFAULT_NAME))]
        HOST_GROUP_COMPUERS_DEFAULT_NAME,

        [Name("Default layout", nameof(Resources.HOST_LAYOUT_GROUPED_DEFAULT_NAME))]
        HOST_LAYOUT_GROUPED_DEFAULT_NAME,

        [Name("Selling point", nameof(Resources.STOCK_SELLING_POINT_DEFAULT_NAME))]
        STOCK_SELLING_POINT_DEFAULT_NAME,
        
        [Name("Warehouse", nameof(Resources.STOCK_WAREHOUSE_DEFAULT_NAME))]
        STOCK_WAREHOUSE_DEFAULT_NAME,

        [Name("I need assistance, please.", nameof(Resources.ASSISTANCE_REQUEST_TYPE_DEFAULT_NAME))]
        ASSISTANCE_REQUEST_TYPE_DEFAULT_NAME,

        [Name("Primary", nameof(Resources.REGISTER_DEFAULT_NAME))]
        REGISTER_DEFAULT_NAME,

        [Name("Global", nameof(Resources.CLIENT_OPTIONS_DEFAULT_NAME))]
        CLIENT_OPTIONS_DEFAULT_NAME,
    }
}
