using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Set for default localized object naming.
    /// </summary>
    public enum DefaultNames
    {
        [Name("Primary", nameof(Resources.BRANCH_DEFAULT_NAME))]
        BRANCH_DEFAULT_NAME,

        [Name("Cash", nameof(Resources.PAYMENT_METHOD_TYPE_CASH_NAME))]
        PAYMENT_METHOD_CASH_NAME,
        
        [Name("Credit Card", nameof(Resources.PAYMENT_METHOD_TYPE_CREDIT_CARD_NAME))]
        PAYMENT_METHOD_CREDIT_CARD_NAME,
        
        [Name("Deposit", nameof(Resources.PAYMENT_METHOD_TYPE_DEPOSIT_NAME))]
        PAYMENT_METHOD_DEPOSIT_NAME,

        [Name("Points", nameof(Resources.PAYMENT_METHOD_TYPE_POINTS_NAME))]
        PAYMENT_METHOD_POINTS_NAME,

        [Name("Endpoints", nameof(Resources.HOST_GROUP_ENDPOINTS_DEFAULT_NAME))]
        HOST_GROUP_ENDPOINTS_DEFAULT_NAME,

        [Name("Computers", nameof(Resources.HOST_GROUP_COMPUERS_DEFAULT_NAME))]
        HOST_GROUP_COMPUERS_DEFAULT_NAME,

        [Name("Default layout", nameof(Resources.HOST_LAYOUT_GROUPED_DEFAULT_NAME))]
        HOST_LAYOUT_GROUPED_DEFAULT_NAME,

        [Name("Selling point", nameof(Resources.STOCK_SELLING_POINT_DEFAULT_NAME))]
        STOCK_SELLING_POINT_DEFAULT_NAME,
        
        [Name("Warehouse", nameof(Resources.STOCK_WAREHOUSE_DEFAULT_NAME))]
        STOCK_WAREHOUSE_DEFAULT_NAME,

        [Name("I need assistance, please.", nameof(Resources.ASSISTANCE_REQUEST_TYPE_DEFAULT_NAME))]
        ASSISTANCE_REQUEST_TYPE_DEFAULT_NAME,

        [Name("Primary", nameof(Resources.REGISTER_DEFAULT_NAME))]
        REGISTER_DEFAULT_NAME,

        [Name("Global", nameof(Resources.CLIENT_OPTIONS_DEFAULT_NAME))]
        CLIENT_OPTIONS_DEFAULT_NAME,

        [Name("Computers prices", nameof(Resources.BILL_PROFILE_COMPUTERS_DEFAULT_NAME))]
        BILL_PROFILE_COMPUTERS_DEFAULT_NAME,

        [Name("Endpoints prices", nameof(Resources.BILL_PROFILE_ENDPOINTS_DEFAULT_NAME))]
        BILL_PROFILE_ENDPOINTS_DEFAULT_NAME,

        [Name("Games", nameof(Resources.APP_CATEGORY_GAMES_DEFAULT_NAME))]
        APP_CATEGORY_GAMES_DEFAULT_NAME,

        [Name("Launchers", nameof(Resources.APP_CATEGORY_LAUNCHERS_DEFAULT_NAME))]
        APP_CATEGORY_LAUNCHERS_DEFAULT_NAME,

        [Name("Applications", nameof(Resources.APP_CATEGORY_APPLICATIONS_DEFAULT_NAME))]
        APP_CATEGORY_APPLICATIONS_DEFAULT_NAME,

        [Name("Default", nameof(Resources.APP_GROUP_DEFAULT_NAME))]
        APP_GROUP_DEFAULT_NAME,

        [Name("Time offers", nameof(Resources.PRODUCT_GROUP_TIME_OFFERS_DEFAULT_NAME))]
        PRODUCT_GROUP_TIME_OFFERS_DEFAULT_NAME,

        [Name("Food", nameof(Resources.PRODUCT_GROUP_FOOD_DEFAULT_NAME))]
        PRODUCT_GROUP_FOOD_DEFAULT_NAME,

        [Name("Drinks", nameof(Resources.PRODUCT_GROUP_DRINKS_DEFAULT_NAME))]
        PRODUCT_GROUP_DRINKS_DEFAULT_NAME,

        [Name("Sweets", nameof(Resources.PRODUCT_GROUP_SWEETS_DEFAULT_NAME))]
        PRODUCT_GROUP_SWEETS_DEFAULT_NAME,
    }
}
