using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Client
{
    public enum ApplicationSortingOption
    {
        [Name("Popularity", nameof(Resources.APPLICATION_SORTING_OPTION_POPULARITY_NAME))]
        Popularity = 0,

        [Name("Add Date", nameof(Resources.APPLICATION_SORTING_OPTION_ADD_DATE_NAME))]
        AddDate = 1,

        [Name("Title", nameof(Resources.APPLICATION_SORTING_OPTION_TITLE_NAME))]
        Title = 2,

        [Name("Use", nameof(Resources.APPLICATION_SORTING_OPTION_USE_NAME))]
        Use = 3,

        [Name("Rating", nameof(Resources.APPLICATION_SORTING_OPTION_RATING_NAME))]
        Rating = 4,

        [Name("Release Date", nameof(Resources.APPLICATION_SORTING_OPTION_RELEASE_DATE_NAME))]
        ReleaseDate = 5,
    }
}
