using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Client power saving.
    /// </summary>
    public enum ClientPowerSaving
    {
        [Name("Disabled", nameof(Resources.CLIENT_POWER_SAVING_DISABLED))]
        Disabled = 0,

        [Name("Shut Down", nameof(Resources.CLIENT_POWER_SAVING_SHUT_DOWN))]
        ShutDown = 1,

        [Name("Sleep", nameof(Resources.CLIENT_POWER_SAVING_SLEEP))]
        Sleep = 2,
    }
}
