using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Client logout actions.
    /// </summary>
    public enum ClientLogoutAction
    {
        /// <summary>
        /// No action.
        /// </summary>
        [Name("No Action", nameof(Resources.CLIENT_LOGOUT_ACTION_NO_ACTION))]
        NoAction = -1,

        /// <summary>
        /// Reboot.
        /// </summary>
        [Name("Reboot", nameof(Resources.CLIENT_LOGOUT_ACTION_REBOOT))]
        Reboot = 0,

        /// <summary>
        /// Close programs.
        /// </summary>
        [Name("Close Programs", nameof(Resources.CLIENT_LOGOUT_ACTION_CLOSE_PROGRAMS))]
        ClosePrograms = 1,

        /// <summary>
        /// Turn off.
        /// </summary>
        [Name("Turn Off", nameof(Resources.CLIENT_LOGOUT_ACTION_TURN_OFF))]
        TurnOff = 2,

        /// <summary>
        /// Log off.
        /// </summary>
        [Name("Log Off", nameof(Resources.CLIENT_LOGOUT_ACTION_LOG_OFF))]
        LogOff = 3,

        /// <summary>
        /// Stand by.
        /// </summary>
        [Name("Stand By", nameof(Resources.CLIENT_LOGOUT_ACTION_STAND_BY))]
        StandBy = 4,

        /// <summary>
        /// Maintenance.
        /// </summary>
        [Name("Admin Mode", nameof(Resources.CLIENT_LOGOUT_ACTION_ADMIN_MODE))]
        AdminMode = 5,
    }
}
