using Gizmo.Shared.Resources.Autogenerated;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Options;

namespace Gizmo.Server.Options
{
    [OptionsConfigurationSection("GRACEPERIOD")]
    [StoreOptionsGroup("GRACE_PERIOD")]
    [MessagePack.MessagePackObject()]
    public sealed class GracePeriodOptions : IStoreOptions
    {
        [Name("Logout enabled", nameof(Resources.SERVER_OPTION_GRACE_PERIOD_LOGOUT_ENABLED_NAME))]
        [ExtendedDescription("Specifies if age is mandatory for all age restrictions", nameof(Resources.SERVER_OPTION_GRACE_PERIOD_LOGOUT_ENABLED_DESCRIPTION))]
        [StoreOptionKey("LOGOUT_ENABLED")]
        [MessagePack.Key(0)]
        public bool IsLogoutEnabled { get; init; }

        [Name("Logout time", nameof(Resources.SERVER_OPTION_GRACE_PERIOD_LOGOUT_TIME_NAME))]
        [ExtendedDescription("Specifies logout grace period time", nameof(Resources.SERVER_OPTION_GRACE_PERIOD_LOGOUT_TIME_DESCRIPTION))]
        [StoreOptionKey("LOGOUT_TIME")]
        [MessagePack.Key(1)]
        public int LogoutTime { get; init; }
    }
}
