using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;
using Microsoft.Extensions.Options;

namespace Gizmo.Server.Options
{
    /// <summary>
    /// Action Center options.
    /// </summary>
    /// <remarks>
    /// One enabled flag and one sound per notification kind. A sound is the guid of an uploaded file served at
    /// <c>/files/{guid}</c>; null plays the built-in default shipped with the Manager. There is no referential
    /// integrity, a file that no longer exists falls back to the default at play time.
    /// </remarks>
    [OptionsConfigurationSection("ACTIONCENTER")]
    [StoreOptionsGroup("ACTION_CENTER")]
    [MessagePack.MessagePackObject()]
    public sealed class ActionCenterOptions : IStoreOptions
    {
        [Name("Logout sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_LOGOUT_SOUND_ENABLED_NAME))]
        [StoreOptionKey("LOGOUT_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(0)]
        public bool LogoutSoundEnabled { get; init; }

        [Name("Logout sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_LOGOUT_SOUND_NAME))]
        [StoreOptionKey("LOGOUT_SOUND")]
        [MessagePack.Key(1)]
        public Guid? LogoutSound { get; init; }

        [Name("Logout with outstanding balance sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_LOGOUT_WITH_DEBT_SOUND_ENABLED_NAME))]
        [StoreOptionKey("LOGOUT_WITH_DEBT_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(2)]
        public bool LogoutWithDebtSoundEnabled { get; init; }

        [Name("Logout with outstanding balance sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_LOGOUT_WITH_DEBT_SOUND_NAME))]
        [StoreOptionKey("LOGOUT_WITH_DEBT_SOUND")]
        [MessagePack.Key(3)]
        public Guid? LogoutWithDebtSound { get; init; }

        [Name("Console session ended sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_CONSOLE_SESSION_ENDED_SOUND_ENABLED_NAME))]
        [StoreOptionKey("CONSOLE_SESSION_ENDED_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(4)]
        public bool ConsoleSessionEndedSoundEnabled { get; init; }

        [Name("Console session ended sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_CONSOLE_SESSION_ENDED_SOUND_NAME))]
        [StoreOptionKey("CONSOLE_SESSION_ENDED_SOUND")]
        [MessagePack.Key(5)]
        public Guid? ConsoleSessionEndedSound { get; init; }

        [Name("Order received sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_ORDER_RECEIVED_SOUND_ENABLED_NAME))]
        [StoreOptionKey("ORDER_RECEIVED_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(6)]
        public bool OrderReceivedSoundEnabled { get; init; }

        [Name("Order received sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_ORDER_RECEIVED_SOUND_NAME))]
        [StoreOptionKey("ORDER_RECEIVED_SOUND")]
        [MessagePack.Key(7)]
        public Guid? OrderReceivedSound { get; init; }

        [Name("Assistance requested sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_ASSISTANCE_REQUESTED_SOUND_ENABLED_NAME))]
        [StoreOptionKey("ASSISTANCE_REQUESTED_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(8)]
        public bool AssistanceRequestedSoundEnabled { get; init; }

        [Name("Assistance requested sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_ASSISTANCE_REQUESTED_SOUND_NAME))]
        [StoreOptionKey("ASSISTANCE_REQUESTED_SOUND")]
        [MessagePack.Key(9)]
        public Guid? AssistanceRequestedSound { get; init; }

        [Name("Host security disabled sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_HOST_SECURITY_DISABLED_SOUND_ENABLED_NAME))]
        [StoreOptionKey("HOST_SECURITY_DISABLED_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(10)]
        public bool HostSecurityDisabledSoundEnabled { get; init; }

        [Name("Host security disabled sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_HOST_SECURITY_DISABLED_SOUND_NAME))]
        [StoreOptionKey("HOST_SECURITY_DISABLED_SOUND")]
        [MessagePack.Key(11)]
        public Guid? HostSecurityDisabledSound { get; init; }

        [Name("Host disconnected sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_HOST_DISCONNECTED_SOUND_ENABLED_NAME))]
        [StoreOptionKey("HOST_DISCONNECTED_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(12)]
        public bool HostDisconnectedSoundEnabled { get; init; }

        [Name("Host disconnected sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_HOST_DISCONNECTED_SOUND_NAME))]
        [StoreOptionKey("HOST_DISCONNECTED_SOUND")]
        [MessagePack.Key(13)]
        public Guid? HostDisconnectedSound { get; init; }

        [Name("User logged in sound enabled", nameof(Resources.SERVER_OPTION_ACTION_CENTER_USER_LOGGED_IN_SOUND_ENABLED_NAME))]
        [StoreOptionKey("USER_LOGGED_IN_SOUND_ENABLED")]
        [DefaultValue(true)]
        [MessagePack.Key(14)]
        public bool UserLoggedInSoundEnabled { get; init; }

        [Name("User logged in sound", nameof(Resources.SERVER_OPTION_ACTION_CENTER_USER_LOGGED_IN_SOUND_NAME))]
        [StoreOptionKey("USER_LOGGED_IN_SOUND")]
        [MessagePack.Key(15)]
        public Guid? UserLoggedInSound { get; init; }
    }
}
