using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;
using Microsoft.Extensions.Options;

namespace Gizmo.Server.Options
{
    [OptionsConfigurationSection("USERLOGOUTGRACE")]
    [StoreOptionsGroup("USER_LOGOUT_GRACE")]
    [MessagePack.MessagePackObject()]
    public sealed class UserLogoutGraceOptions : IStoreOptions
    {
        [Name("Enabled", nameof(Resources.SERVER_OPTION_USER_LOGOUT_GRACE_PERIOD_ENABLED_NAME))]
        [ExtendedDescription("Specifies if user logout grace period is enabled", nameof(Resources.SERVER_OPTION_USER_LOGOUT_GRACE_PERIOD_ENABLED_DESCRIPTION))]
        [StoreOptionKey("ENABLED")]
        [MessagePack.Key(0)]
        public bool IsEnabled { get; init; }

        [Name("Grace time", nameof(Resources.SERVER_OPTION_USER_LOGOUT_GRACE_PERIOD_TIME_NAME))]
        [ExtendedDescription("Specifies logout grace period time", nameof(Resources.SERVER_OPTION_USER_LOGOUT_GRACE_PERIOD_TIME_DESCRIPTION))]
        [StoreOptionKey("TIME")]
        [MessagePack.Key(1)]
        public int Time { get; init; }
    }
}
