using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;
using Microsoft.Extensions.Options;

namespace Gizmo.Server.Options
{
    /// <summary>
    /// User search options.
    /// </summary>
    [OptionsConfigurationSection("USERSEARCH")]
    [StoreOptionsGroup("USER_SEARCH")]
    [MessagePack.MessagePackObject()]
    public sealed class UserSearchOptions : IStoreOptions
    {
        /// <summary>
        /// Gets the order the searched fields rank in, highest priority first.
        /// </summary>
        /// <remarks>
        /// Comma separated <see cref="UserSearchFieldType"/> member names, see <see cref="UserSearchFieldPriority"/> for the
        /// value shape. No default value is declared, an unset option is the default order and <see cref="UserSearchFieldPriority"/>
        /// owns it, holding the order in one place rather than repeating it as a literal that could drift from the enum.
        /// </remarks>
        [Name("User search field priority", nameof(Resources.SERVER_OPTION_USER_SEARCH_FIELD_PRIORITY_NAME))]
        [ExtendedDescription("Order the user search fields rank in, best match first", nameof(Resources.SERVER_OPTION_USER_SEARCH_FIELD_PRIORITY_DESCRIPTION))]
        [StoreOptionKey("FIELD_PRIORITY")]
        [UserSearchFieldPriorityValidation]
        [MessagePack.Key(0)]
        public string? FieldPriority { get; init; }
    }
}
