using Gizmo.Server.Security;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Gizmo permissions.
    /// </summary>
    /// <remarks>
    /// Defines permissions/policies supported by application.
    /// </remarks>
    public enum GizmoPolicies
    {
        #region SALE
        /// <summary>
        /// Sale permission.
        /// </summary>
        [PolicyDescription("Sale", "*", GizmoPolicyGroups.Sales, nameof(Resources.GIZMO_POLICY_SALE_NAME), nameof(Resources.GIZMO_POLICY_SALE_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Sale,

        /// <summary>
        /// Sale at custom permission.
        /// </summary>
        [PolicyDescription("Sale", "CustomPrice", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_CUSTOM_PRICE_NAME), nameof(Resources.GIZMO_POLICY_SALE_CUSTOM_PRICE_DESCRIPTION), [GizmoPolicySet.Owner])]
        SaleCustomPrice,

        /// <summary>
        /// Sale with non default vat permission.
        /// </summary>
        [PolicyDescription("Sale", "NonDefaultVat", GizmoPolicyGroups.Sales, [Sale], "PERMISSION_GROUP_SALE", "PERMISSION_ACTION_SALE_NON_DEFAULT_VAT", [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner], IsAssignable = false)]
        SaleNonDefaultVat,

        /// <summary>
        /// Sale with pay later permission.
        /// </summary>
        [PolicyDescription("Sale", "PayLater", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_PAY_LATER_NAME), nameof(Resources.GIZMO_POLICY_SALE_PAY_LATER_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        SaleNonPayLater,

        /// <summary>
        /// Sale void invoice permission.
        /// </summary>
        [PolicyDescription("Sale", "VoidInvoices", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_VOID_INVOICE_NAME), nameof(Resources.GIZMO_POLICY_SALE_VOID_INVOICE_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        SaleNoVoidInvoices,

        /// <summary>
        /// Void used time invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "VoidUsedTimeInvoices", GizmoPolicyGroups.Sales, [SaleNoVoidInvoices], nameof(Resources.GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_NAME), nameof(Resources.GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        VoidUsedTimeInvoices,

        /// <summary>
        /// Void closed shift invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "VoidClosedShiftInvoices", GizmoPolicyGroups.Sales, [SaleNoVoidInvoices], nameof(Resources.GIZMO_POLICY_SALE_VOID_CLOSED_SHIFT_INVOICE_NAME), nameof(Resources.GIZMO_POLICY_SALE_VOID_CLOSED_SHIFT_INVOICE_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        VoidClosedShiftInvoices,

        /// <summary>
        /// Void other operator invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "VoidOtherOperatorInvoices", GizmoPolicyGroups.Sales, [SaleNoVoidInvoices], nameof(Resources.GIZMO_POLICY_SALE_VOID_NON_OWNED_INVOICE_NAME), nameof(Resources.GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        VoidOtherOperatorInvoices,

        /// <summary>
        /// Void previous business day invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "VoidPastDaysInvoices", GizmoPolicyGroups.Sales, [SaleNoVoidInvoices], nameof(Resources.GIZMO_POLICY_SALE_VOID_PAST_DAY_INVOICE_NAME), nameof(Resources.GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        VoidPastDaysInvoices,

        /// <summary>
        /// Sale deposit permission.
        /// </summary>
        [PolicyDescription("Sale", "Deposit", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_GROUP_DEPLOYMENT_NAME), nameof(Resources.GIZMO_POLICY_SALE_DEPOSIT_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Deposit,

        /// <summary>
        /// Sale withdraw permission.
        /// </summary>
        [PolicyDescription("Sale", "Withdraw", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_WITHDRAW_NAME), nameof(Resources.GIZMO_POLICY_SALE_WITHDRAW_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Withdraw,

        /// <summary>
        /// Sale void deposits permission.
        /// </summary>
        [PolicyDescription("Sale", "VoidDeposits", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_VOID_DEPOSIT_NAME), nameof(Resources.GIZMO_POLICY_SALE_VOID_DEPOSIT_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        VoidDeposits,

        /// <summary>
        /// Sale manual open cash drawer permission.
        /// </summary>
        [PolicyDescription("Sale", "ManualOpenCashDrawer", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_OPEN_CASH_DRAWER_NAME), nameof(Resources.GIZMO_POLICY_SALE_OPEN_CASH_DRAWER_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        SaleManualOpenCashDrawer,

        /// <summary>
        /// Sale modify billing options permission.
        /// </summary>
        [PolicyDescription("Sale", "ModifyBillingOptions", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_MODIFY_USER_BILLING_OPTIONS_NAME), nameof(Resources.GIZMO_POLICY_SALE_MODIFY_USER_BILLING_OPTIONS_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        SaleModifyBillingOptions,

        /// <summary>
        /// Sale allow time credit permission.
        /// </summary>
        [PolicyDescription("Sale", "AllowTimeCredit", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_ALLOW_TIME_CREDIT_NAME), nameof(Resources.GIZMO_POLICY_SALE_ALLOW_TIME_CREDIT_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        AllowTimeCredit,

        /// <summary>
        /// Sale disable receipt print permission.
        /// </summary>
        [PolicyDescription("Sale", "AllowDisableReceiptPrint", GizmoPolicyGroups.Sales, [Sale], nameof(Resources.GIZMO_POLICY_SALE_DISABLE_RECEIPT_PRINT_NAME), nameof(Resources.GIZMO_POLICY_SALE_DISABLE_RECEIPT_PRINT_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        SaleAllowDisableReceiptPrint,

        /// <summary>
        /// View invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "ViewInvoices", GizmoPolicyGroups.Sales, nameof(Resources.GIZMO_POLICY_SALE_VIEW_INVOICES_NAME), nameof(Resources.GIZMO_POLICY_SALE_VIEW_INVOICES_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ViewInvoices,

        /// <summary>
        /// View only unpaid invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "ViewPaidInvoices", GizmoPolicyGroups.Sales, [ViewInvoices], nameof(Resources.GIZMO_POLICY_SALE_VIEW_PAID_INVOICES_NAME), nameof(Resources.GIZMO_POLICY_SALE_VIEW_PAID_INVOICES_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ViewPaidInvoices,

        /// <summary>
        /// View only business day invoices permission.
        /// </summary>
        [PolicyDescription("Sale", "ViewPastDaysInvoices", GizmoPolicyGroups.Sales, [ViewInvoices], nameof(Resources.GIZMO_POLICY_SALE_VIEW_PAST_DAY_INVOICES_NAME), nameof(Resources.GIZMO_POLICY_SALE_VIEW_PAST_DAY_INVOICES_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ViewPastDaysInvoices,

        /// <summary>
        /// View deposits permission.
        /// </summary>
        [PolicyDescription("Sale", "ViewDeposits", GizmoPolicyGroups.Sales, nameof(Resources.GIZMO_POLICY_SALE_VIEW_DEPOSITS_NAME), nameof(Resources.GIZMO_POLICY_SALE_VIEW_DEPOSITS_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ViewDeposits,

        /// <summary>
        /// View only business day deposits permission.
        /// </summary>
        [PolicyDescription("Sale", "ViewPastDaysDeposits", GizmoPolicyGroups.Sales, [ViewDeposits], nameof(Resources.GIZMO_POLICY_SALE_VIEW_PAST_DAY_DEPOSITS_NAME), nameof(Resources.GIZMO_POLICY_SALE_VIEW_PAST_DAY_DEPOSITS_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ViewPastDaysDeposits,

        /// <summary>
        /// Sale delete time purchases permission.
        /// </summary>
        [PolicyDescription("Sale", "DeleteTimePurchases", GizmoPolicyGroups.Sales, nameof(Resources.GIZMO_POLICY_SALE_DELETE_TIME_PURCHASES_NAME), nameof(Resources.GIZMO_POLICY_SALE_DELETE_TIME_PURCHASES_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        SaleNoDeleteTimePurchases,

        #endregion

        #region SHIFT
        /// <summary>
        /// Shift view expected permission.
        /// </summary>
        [PolicyDescription("Shift", "ViewExpected", GizmoPolicyGroups.Shift, nameof(Resources.GIZMO_POLICY_SHIFT_COUNT_VIEW_EXPECTED_NAME), nameof(Resources.GIZMO_POLICY_SHIFT_COUNT_VIEW_EXPECTED_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ShiftCountViewExpected,
        #endregion

        #region STOCK

        /// <summary>
        /// Stock permission.
        /// </summary>
        [PolicyDescription("Stock", "*", GizmoPolicyGroups.Stock, nameof(Resources.GIZMO_POLICY_STOCK_NAME), nameof(Resources.GIZMO_POLICY_STOCK_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Stock,

        /// <summary>
        /// Stock permission.
        /// </summary>
        [PolicyDescription("Stock", "Manage", GizmoPolicyGroups.Stock, [Stock], nameof(Resources.GIZMO_POLICY_STOCK_MANAGE_NAME), nameof(Resources.GIZMO_POLICY_STOCK_MANAGE_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        StockManage,

        /// <summary>
        /// Stock permission.
        /// </summary>
        [PolicyDescription("Stock", "ViewStockTransactions", GizmoPolicyGroups.Stock, nameof(Resources.GIZMO_POLICY_STOCK_VIEW_TRANSACTIONS_NAME), nameof(Resources.GIZMO_POLICY_STOCK_VIEW_TRANSACTIONS_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        StockViewTransactions,

        /// <summary>
        /// Stock permission.
        /// </summary>
        [PolicyDescription("Stock", "ViewPastDaysStockTransactions", GizmoPolicyGroups.Stock, [StockViewTransactions], nameof(Resources.GIZMO_POLICY_STOCK_VIEW_PAST_DAY_TRANSACTIONS_NAME), nameof(Resources.GIZMO_POLICY_STOCK_VIEW_PAST_DAY_TRANSACTIONS_DESCRIPTIONS),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        StockViewPastDayTransactions,

        #endregion

        #region MANAGEMENT

        /// <summary>
        /// Management permission.
        /// </summary>
        [PolicyDescription("Management", "*", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        Management,

        /// <summary>
        /// Management access tasks permission.
        /// </summary>
        [PolicyDescription("Management", "Tasks", GizmoPolicyGroups.Management, [Management], nameof(Resources.GIZMO_POLICY_MANAGEMENT_TASKS_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_TASKS_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        ManagementTasks,

        /// <summary>
        /// Management access processes permission.
        /// </summary>
        [PolicyDescription("Management", "Processes", GizmoPolicyGroups.Management, [Management], nameof(Resources.GIZMO_POLICY_MANAGEMENT_PROCESSES_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_PROCESSES_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ManageProcesses,

        /// <summary>
        /// Management access files permission.
        /// </summary>
        [PolicyDescription("Management", "Files", GizmoPolicyGroups.Management, [Management], nameof(Resources.GIZMO_POLICY_MANAGEMENT_FILES_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_FILES_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        ManageFiles,

        /// <summary>
        /// Management maintenance mode permission.
        /// </summary>
        [PolicyDescription("Management", "Maintenance", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_MAINTENANCE_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_MAINTENANCE_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        ManageMaintenance,

        /// <summary>
        /// Management security permission.
        /// </summary>
        [PolicyDescription("Management", "Security", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_SECURITY_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_SECURITY_DESCRIPTION),
            [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        ManageSecurity,

        /// <summary>
        /// Management lock state permission.
        /// </summary>
        [PolicyDescription("Management", "LockState", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_LOCK_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_LOCK_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ManageLockState,

        /// <summary>
        /// Management module restart permission.
        /// </summary>
        [PolicyDescription("Management", "ModuleRestart", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_CLIENT_MODULE_RESTART_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_CLIENT_MODULE_RESTART_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ManageModuleRestart,

        /// <summary>
        /// Management power on endpoints permission.
        /// </summary>
        [PolicyDescription("Management", "PowerOnEndpoints", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_TURN_ON_ENDPOINTS_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_TURN_ON_ENDPOINTS_DESCRIPTION),
            [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        ManagePowerOnEndpoints,

        /// <summary>
        /// Management edit layouts permission.
        /// </summary>
        [PolicyDescription("Management", "EditLayouts", GizmoPolicyGroups.Management, nameof(Resources.GIZMO_POLICY_MANAGEMENT_EDIT_LAYOUT_NAME), nameof(Resources.GIZMO_POLICY_MANAGEMENT_EDIT_LAYOUT_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ManageEditLayouts,

        #endregion

        /// <summary>
        /// Deployment permission.
        /// </summary>
        [PolicyDescription("Deployment", "*", GizmoPolicyGroups.Deployment, nameof(Resources.GIZMO_POLICY_DEPLOYMENT_NAME), nameof(Resources.GIZMO_POLICY_DEPLOYMENT_DESCRIPTION),
             [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        Deployment,

        /// <summary>
        /// Monitoring permission.
        /// </summary>
        [PolicyDescription("Monitoring", "*", GizmoPolicyGroups.Monitoring, nameof(Resources.GIZMO_POLICY_MONITORING_NAME), nameof(Resources.GIZMO_POLICY_MONITORING_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner, GizmoPolicySet.Marketer])]
        Monitoring,

        /// <summary>
        /// Reports permission.
        /// </summary>
        [PolicyDescription("Reports", "*", GizmoPolicyGroups.Reports, nameof(Resources.GIZMO_POLICY_REPORTS_NAME), nameof(Resources.GIZMO_POLICY_REPORTS_DESCRIPTION), [GizmoPolicySet.Marketer, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Reports,

        /// <summary>
        /// Server settings permission.
        /// </summary>
        [PolicyDescription("Settings", "*", GizmoPolicyGroups.ServerSettings, nameof(Resources.GIZMO_POLICY_SETTINGS_NAME), nameof(Resources.GIZMO_POLICY_SETTINGS_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        ServerSettings,

        /// <summary>
        /// Applications permission.
        /// </summary>
        [PolicyDescription("Apps", "*", GizmoPolicyGroups.Applications, nameof(Resources.GIZMO_POLICY_APPLICATIONS_NAME), nameof(Resources.GIZMO_POLICY_APPLICATIONS_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Applications,

        /// <summary>
        /// News permission.
        /// </summary>
        [PolicyDescription("News", "*", GizmoPolicyGroups.News, nameof(Resources.GIZMO_POLICY_NEWS_NAME), nameof(Resources.GIZMO_POLICY_NEWS_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        News,

        #region USER

        /// <summary>
        /// Reset user password permission.
        /// </summary>
        [PolicyDescription("User", "UserPasswordReset", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_PASSWORD_RESET_NAME), nameof(Resources.GIZMO_POLICY_USER_PASSWORD_RESET_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserResetPassword,

        /// <summary>
        /// Enable user permission.
        /// </summary>
        [PolicyDescription("User", "UserEnable", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_UNBAN_NAME), nameof(Resources.GIZMO_POLICY_USER_UNBAN_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserEnable,

        /// <summary>
        /// Disable user permission.
        /// </summary>
        [PolicyDescription("User", "UserDisable", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_BAN_NAME), nameof(Resources.GIZMO_POLICY_USER_BAN_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserDisable,

        /// <summary>
        /// Manual user login permission.
        /// </summary>
        [PolicyDescription("User", "UserManualLogin", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_MANUAL_LOGIN_NAME), nameof(Resources.GIZMO_POLICY_USER_MANUAL_LOGIN_DESCRIPTION), [GizmoPolicySet.Owner])]
        UserManualLogin,

        /// <summary>
        /// Add user permission.
        /// </summary>
        [PolicyDescription("User", "Add", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_CREATE_NAME), nameof(Resources.GIZMO_POLICY_USER_CREATE_DESCRIPTION),
             [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserAdd,

        /// <summary>
        /// Delete user permission.
        /// </summary>
        [PolicyDescription("User", "Delete", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_DELETE_NAME), nameof(Resources.GIZMO_POLICY_USER_DELETE_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserDelete,

        /// <summary>
        /// Delete user permission.
        /// </summary>
        [PolicyDescription("User", "HardDelete", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_HARD_DELETE_NAME), nameof(Resources.GIZMO_POLICY_USER_HARD_DELETE_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserHardDelete,

        /// <summary>
        /// Change user name permission.
        /// </summary>
        [PolicyDescription("User", "ChangeUserName", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_RENAME_NAME), nameof(Resources.GIZMO_POLICY_USER_RENAME_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserChangeUserName,

        /// <summary>
        /// Change user group permission.
        /// </summary>
        [PolicyDescription("User", "ChangeUserGroup", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_CHANGE_GROUP_NAME), nameof(Resources.GIZMO_POLICY_USER_CHANGE_GROUP_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserChangeUserGroup,

        /// <summary>
        /// Edit user permission.
        /// </summary>
        [PolicyDescription("User", "Edit", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_EDIT_NAME), nameof(Resources.GIZMO_POLICY_USER_EDIT_DESCRIPTION),
            [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        UserEdit,

        /// <summary>
        /// Edit user permission.
        /// </summary>
        [PolicyDescription("User", "AccessStats", GizmoPolicyGroups.User, nameof(Resources.GIZMO_POLICY_USER_VIEW_STATS_NAME), nameof(Resources.GIZMO_POLICY_USER_VIEW_STATS_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Marketer, GizmoPolicySet.Owner])]
        UserAccessStats,

        #endregion

        #region LOG

        /// <summary>
        /// Access log permission.
        /// </summary>
        [PolicyDescription("Log", "*", GizmoPolicyGroups.Log, nameof(Resources.GIZMO_POLICY_LOG_NAME), nameof(Resources.GIZMO_POLICY_LOG_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        Log,

        /// <summary>
        /// Clear log permission.
        /// </summary>
        [PolicyDescription("Log", "Clear", GizmoPolicyGroups.Log, [Log], nameof(Resources.GIZMO_POLICY_LOG_CLEAR_NAME), nameof(Resources.GIZMO_POLICY_LOG_CLEAR_DESCRIPTION), [GizmoPolicySet.Technician, GizmoPolicySet.Owner])]
        LogClear,

        #endregion

        #region WAITING_LINES

        /// <summary>
        /// Access waiting lines permission.
        /// </summary>
        [PolicyDescription("WaitingLines", "*", GizmoPolicyGroups.WaitingLines, nameof(Resources.GIZMO_POLICY_GROUP_WAITING_LINES_NAME), nameof(Resources.GIZMO_POLICY_WAITING_LINES_DESCRIPTION),
            [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        WaitingLines,

        /// <summary>
        /// Manage waiting lines permission.
        /// </summary>
        [PolicyDescription("WaitingLines", "Manage", GizmoPolicyGroups.WaitingLines, [WaitingLines], nameof(Resources.GIZMO_POLICY_WAITING_LINES_MANAGE_NAME), nameof(Resources.GIZMO_POLICY_WAITING_LINES_MANAGE_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        WaitingLinesManage,

        #endregion

        #region REGISTER_TRANSACTIONS

        /// <summary>
        /// View register transactions permission.
        /// </summary>
        [PolicyDescription("Register", "ViewRegisterTransactions", GizmoPolicyGroups.Register, nameof(Resources.GIZMO_POLICY_REGISTER_VIEW_TRANSACTIONS_NAME), nameof(Resources.GIZMO_POLICY_REGISTER_VIEW_TRANSACTIONS_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        RegisterViewTransactions,

        /// <summary>
        /// View only business day register transactions permission.
        /// </summary>
        [PolicyDescription("Register", "ViewPastDaysRegisterTransactions", GizmoPolicyGroups.Register, [RegisterViewTransactions], nameof(Resources.GIZMO_POLICY_REGISTER_VIEW_PAST_DAY_TRANSACTIONS_NAME), nameof(Resources.GIZMO_POLICY_REGISTER_VIEW_PAST_DAY_TRANSACTIONS_DESCRIPTION), [GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        RegisterViewPastDaysTransactions,

        /// <summary>
        /// Create pay in register transactions permission.
        /// </summary>

        [PolicyDescription("RegisterTransactions", "RegisterTransactionsPayIn", GizmoPolicyGroups.Register, nameof(Resources.GIZMO_POLICY_REGISTER_PAY_IN_NAME), nameof(Resources.GIZMO_POLICY_REGISTER_PAY_IN_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        RegisterTransactionsPayIn,

        /// <summary>
        /// Create pay out register transactions permission.
        /// </summary>
        [PolicyDescription("RegisterTransactions", "RegisterTransactionsPayOut", GizmoPolicyGroups.Register, nameof(Resources.GIZMO_POLICY_REGISTER_PAY_OUT_NAME), nameof(Resources.GIZMO_POLICY_SALE_PAY_LATER_DESCRIPTION), [GizmoPolicySet.Cashier, GizmoPolicySet.Manager, GizmoPolicySet.Owner])]
        RegisterTransactionsPayOut,

        #endregion

        #region WEB API
        [PolicyDescription("WebApi", "*", GizmoPolicyGroups.WebApi, "PERMISSION_GROUP_WEB_API", "PERMISSION_ACTION_WEB_API", IsAssignable = false)]
        WebApi,
        #endregion
    }
}
