using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Policy groups.
    /// </summary>
    public enum PolicyGroups
    {
        [PolicyGroup(GizmoPolicies.Sale)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SALES_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SALES_DESCRIPTION))]
        Sales,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SHIFT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SHIFT_DESCRIPTION))]
        Shift,

        [PolicyGroup(GizmoPolicies.Stock)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_STOCK_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_STOCK_DESCRIPTION))]
        Stock,

        [PolicyGroup(GizmoPolicies.Monitoring)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_MONITORING_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_STOCK_DESCRIPTION))]
        Monitoring,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_DEPLOYMENT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_DEPLOYMENT_DESCRIPTION))]
        Deployment,

        [PolicyGroup(GizmoPolicies.Reports)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_REPORTS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_REPORTS_DESCRIPTION))]
        Reports,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SERVER_SETTINGS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SERVER_SETTINGS_DESCRIPTION))]
        ServerSettings,

        [PolicyGroup(GizmoPolicies.Applications)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_APPLICATIONS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_APPLICATIONS_DESCRIPTION))]
        Applications,

        [PolicyGroup(GizmoPolicies.News)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_NEWS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_NEWS_DESCRIPTION))]
        News,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_USER_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_USER_DESCRIPTION))]
        User,

        [PolicyGroup(GizmoPolicies.Log)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_LOG_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_LOG_DESCRIPTION))]
        Log,

        [PolicyGroup(GizmoPolicies.WaitingLines)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_WAITING_LINES_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_WEB_API_DESCRIPTION))]
        WaitingLines,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_REGISTER_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_REGISTER_DESCRIPTION))]
        Register,

        [PolicyGroup(GizmoPolicies.WebApi)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_WEB_API_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_WEB_API_DESCRIPTION))]
        WebApi,

        [PolicyGroup(GizmoPolicies.Management)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_MANAGEMENT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_MANAGEMENT_DESCRIPTION))]
        Management ,
    }
}
