//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Shared.Resources.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_ADVANCE {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_ADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full payment.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_FULL_PAYMENT {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_FULL_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full prepayment.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_FULL_PREPAYMENT {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_FULL_PREPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_PREPAYMENT {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_PREPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Date.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_ADD_DATE_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_ADD_DATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_POPULARITY_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_POPULARITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_RATING_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_RATING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_RELEASE_DATE_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_RELEASE_DATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_TITLE_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string APPLICATION_SORTING_OPTION_USE_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_SORTING_OPTION_USE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Mode.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_ADMIN_MODE {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_ADMIN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Programs.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_CLOSE_PROGRAMS {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_CLOSE_PROGRAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_LOG_OFF {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_LOG_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Action.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_NO_ACTION {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_NO_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_REBOOT {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand By.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_STAND_BY {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_STAND_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        public static string CLIENT_LOGOUT_ACTION_TURN_OFF {
            get {
                return ResourceManager.GetString("CLIENT_LOGOUT_ACTION_TURN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string CLIENT_POWER_SAVING_DISABLED {
            get {
                return ResourceManager.GetString("CLIENT_POWER_SAVING_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down.
        /// </summary>
        public static string CLIENT_POWER_SAVING_SHUT_DOWN {
            get {
                return ResourceManager.GetString("CLIENT_POWER_SAVING_SHUT_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string CLIENT_POWER_SAVING_SLEEP {
            get {
                return ResourceManager.GetString("CLIENT_POWER_SAVING_SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable print receipt by default.
        /// </summary>
        public static string DISABLE_PRINT_RECEIPT_BY_DEFAULT {
            get {
                return ResourceManager.GetString("DISABLE_PRINT_RECEIPT_BY_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_FIFTEEN {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_FIFTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_FIVE {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_TEN {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_THIRTY {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_THIRTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_TWENTY {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_TWENTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_TWENTY_FIVE {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_TWENTY_FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string DISK_SPACE_ALLOCATIONS_ZERO {
            get {
                return ResourceManager.GetString("DISK_SPACE_ALLOCATIONS_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the applications feature, enabling the user to manage and interact with applications.
        /// </summary>
        public static string GIZMO_POLICY_APPLICATIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_APPLICATIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_APPLICATIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_APPLICATIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the file copy and deployment feature, enabling the user to manage deployments.
        /// </summary>
        public static string GIZMO_POLICY_DEPLOYMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_DEPLOYMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_DEPLOYMENT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_DEPLOYMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for managing application access and settings..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_APPLICATIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_APPLICATIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_APPLICATIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_APPLICATIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for managing application and service deployments..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_DEPLOYMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_DEPLOYMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_DEPLOYMENT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_DEPLOYMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for accessing and managing logs..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_LOG_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_LOG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_LOG_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_LOG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for system and operations management..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_MANAGEMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_MANAGEMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_MANAGEMENT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_MANAGEMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for system and operational monitoring..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_MONITORING_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_MONITORING_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_MONITORING_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_MONITORING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies related to managing and displaying news content..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_NEWS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_NEWS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_NEWS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_NEWS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for managing register operations and settings..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_REGISTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_REGISTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_REGISTER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_REGISTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for creating, accessing, and managing reports..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_REPORTS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_REPORTS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_REPORTS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_REPORTS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies governing reservations..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_RESERVATIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_RESERVATIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_RESERVATONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_RESERVATONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies related to managing and monitoring sales..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_SALES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_SALES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_SALES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_SALES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies related to server configuration and settings..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_SERVER_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_SERVER_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_SERVER_SETTINGS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_SERVER_SETTINGS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies governing shifts and sales operations during shifts..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_SHIFT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_SHIFT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_SHIFT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_SHIFT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for managing and accessing stock inventory..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_STOCK_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_STOCK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_STOCK_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_STOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for user management and access..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_USER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_USER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_USER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for managing access to waiting lines..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_WAITING_LINES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_WAITING_LINES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Lines.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_WAITING_LINES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_WAITING_LINES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies for accessing and managing Web API functionality..
        /// </summary>
        public static string GIZMO_POLICY_GROUP_WEB_API_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_WEB_API_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API.
        /// </summary>
        public static string GIZMO_POLICY_GROUP_WEB_API_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_GROUP_WEB_API_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the log management feature enabling the user to clear system logs.
        /// </summary>
        public static string GIZMO_POLICY_LOG_CLEAR_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_LOG_CLEAR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string GIZMO_POLICY_LOG_CLEAR_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_LOG_CLEAR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the log feature enabling the user to view system logs.
        /// </summary>
        public static string GIZMO_POLICY_LOG_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_LOG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_LOG_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_LOG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the restart feature enabling the user to restart the client module.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_CLIENT_MODULE_RESTART_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_CLIENT_MODULE_RESTART_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart client module.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_CLIENT_MODULE_RESTART_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_CLIENT_MODULE_RESTART_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the management feature enabling the user to perform administrative tasks.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to edit layouts.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_EDIT_LAYOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_EDIT_LAYOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit layouts.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_EDIT_LAYOUT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_EDIT_LAYOUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the client host files feature enabling the user to manage and interact with host files.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_FILES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_FILES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_FILES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_FILES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manage the client host keyboard and mouse input lock state enabling the user to control input permissions.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_LOCK_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_LOCK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lock.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_LOCK_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_LOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manage the client host maintenance state enabling the user to control and update its maintenance status.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_MAINTENANCE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_MAINTENANCE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage maintenance.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_MAINTENANCE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_MAINTENANCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the client hosts processes feature enabling the user to view and manage running processes.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_PROCESSES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_PROCESSES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage processes.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_PROCESSES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_PROCESSES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manage the client host security state enabling the user to control and update security settings.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_SECURITY_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_SECURITY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_SECURITY_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_SECURITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the tasks feature enabling the user to view and manage tasks.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_TASKS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_TASKS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access tasks.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_TASKS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_TASKS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually turn on endpoints enabling the user to control endpoint power states.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_TURN_ON_ENDPOINTS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_TURN_ON_ENDPOINTS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on endpoints.
        /// </summary>
        public static string GIZMO_POLICY_MANAGEMENT_TURN_ON_ENDPOINTS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MANAGEMENT_TURN_ON_ENDPOINTS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the screen monitoring feature enabling the user to view and monitor client screens.
        /// </summary>
        public static string GIZMO_POLICY_MONITORING_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MONITORING_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_MONITORING_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_MONITORING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the news and marketing feature enabling the user to view and manage related content.
        /// </summary>
        public static string GIZMO_POLICY_NEWS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_NEWS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_NEWS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_NEWS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to perform register pay-ins enabling the user to add funds to the register.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_PAY_IN_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_PAY_IN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make pay-ins.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_PAY_IN_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_PAY_IN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to perform register pay-outs enabling the user to withdraw funds from the register.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_PAY_OUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_PAY_OUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make pay-outs.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_PAY_OUT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_PAY_OUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view past day register transactions enabling the user to review previous register activities.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_VIEW_PAST_DAY_TRANSACTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_VIEW_PAST_DAY_TRANSACTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View past day transactions.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_VIEW_PAST_DAY_TRANSACTIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_VIEW_PAST_DAY_TRANSACTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view register transactions enabling the user to review all register activities.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_VIEW_TRANSACTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_VIEW_TRANSACTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View transactions.
        /// </summary>
        public static string GIZMO_POLICY_REGISTER_VIEW_TRANSACTIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REGISTER_VIEW_TRANSACTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the reports feature enabling the user to view and generate reports.
        /// </summary>
        public static string GIZMO_POLICY_REPORTS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REPORTS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_REPORTS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_REPORTS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant access to reservations.
        /// </summary>
        public static string GIZMO_POLICY_RESERVATIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_RESERVATIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_RESERVATIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_RESERVATIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant access to create reservations without payments.
        /// </summary>
        public static string GIZMO_POLICY_RESERVATIONS_WITHOUT_PAYMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_RESERVATIONS_WITHOUT_PAYMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create reservations without payments.
        /// </summary>
        public static string GIZMO_POLICY_RESERVATIONS_WITHOUT_PAYMENT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_RESERVATIONS_WITHOUT_PAYMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow time credit.
        /// </summary>
        public static string GIZMO_POLICY_SALE_ALLOW_TIME_CREDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_ALLOW_TIME_CREDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow time credit.
        /// </summary>
        public static string GIZMO_POLICY_SALE_ALLOW_TIME_CREDIT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_ALLOW_TIME_CREDIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to make sales at custom prices enabling the user to override default pricing.
        /// </summary>
        public static string GIZMO_POLICY_SALE_CUSTOM_PRICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_CUSTOM_PRICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom price.
        /// </summary>
        public static string GIZMO_POLICY_SALE_CUSTOM_PRICE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_CUSTOM_PRICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to delete time purchases enabling the user to remove fixed time or time offer transactions.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DELETE_TIME_PURCHASES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DELETE_TIME_PURCHASES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete time purchases.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DELETE_TIME_PURCHASES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DELETE_TIME_PURCHASES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to make deposits enabling the user to add funds to customer accounts.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DEPOSIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DEPOSIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DEPOSIT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DEPOSIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to make sales enabling the user to process customer purchases.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to selectively disable receipt printing enabling the user to manage receipt generation preferences.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DISABLE_RECEIPT_PRINT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DISABLE_RECEIPT_PRINT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable receipt printing.
        /// </summary>
        public static string GIZMO_POLICY_SALE_DISABLE_RECEIPT_PRINT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_DISABLE_RECEIPT_PRINT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually select user billing options enabling the user to customize billing preferences for customers.
        /// </summary>
        public static string GIZMO_POLICY_SALE_MODIFY_USER_BILLING_OPTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_MODIFY_USER_BILLING_OPTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user billing options.
        /// </summary>
        public static string GIZMO_POLICY_SALE_MODIFY_USER_BILLING_OPTIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_MODIFY_USER_BILLING_OPTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_SALE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually open the cash drawer enabling the user to override automatic controls.
        /// </summary>
        public static string GIZMO_POLICY_SALE_OPEN_CASH_DRAWER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_OPEN_CASH_DRAWER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open cash drawer.
        /// </summary>
        public static string GIZMO_POLICY_SALE_OPEN_CASH_DRAWER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_OPEN_CASH_DRAWER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to enable pay later options allowing the user to defer payment for transactions.
        /// </summary>
        public static string GIZMO_POLICY_SALE_PAY_LATER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_PAY_LATER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay later.
        /// </summary>
        public static string GIZMO_POLICY_SALE_PAY_LATER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_PAY_LATER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view deposits enabling the user to review customer account deposit transactions.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_DEPOSITS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_DEPOSITS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View deposits.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_DEPOSITS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_DEPOSITS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view invoices enabling the user to review billing and payment details.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_INVOICES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_INVOICES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_INVOICES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_INVOICES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view paid invoices enabling the user to review completed payment records.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_PAID_INVOICES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_PAID_INVOICES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View paid invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_PAID_INVOICES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_PAID_INVOICES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view past day deposits enabling the user to review deposit transactions from the previous day.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_PAST_DAY_DEPOSITS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_PAST_DAY_DEPOSITS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View past day deposits.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_PAST_DAY_DEPOSITS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_PAST_DAY_DEPOSITS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view past day invoices enabling the user to review invoices issued on the previous day.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_PAST_DAY_INVOICES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_PAST_DAY_INVOICES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View past day invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VIEW_PAST_DAY_INVOICES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VIEW_PAST_DAY_INVOICES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void invoices from closed shifts enabling the user to cancel transactions after the shift has ended.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_CLOSED_SHIFT_INVOICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_CLOSED_SHIFT_INVOICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void closed shift invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_CLOSED_SHIFT_INVOICE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_CLOSED_SHIFT_INVOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void deposits enabling the user to cancel or reverse deposit transactions.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_DEPOSIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_DEPOSIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void deposit.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_DEPOSIT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_DEPOSIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void invoices enabling the user to cancel or reverse issued invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_INVOICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_INVOICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_INVOICE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_INVOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void invoices issued in differnt branch.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_NON_CURRENT_BRANCH_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_NON_CURRENT_BRANCH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void non current branch invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_NON_CURRENT_BRANCH_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_NON_CURRENT_BRANCH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void invoices created by other operators enabling the user to cancel transactions initiated by different users.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_NON_OWNED_INVOICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_NON_OWNED_INVOICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void non owned invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_NON_OWNED_INVOICE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_NON_OWNED_INVOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void invoices created on past dates enabling the user to cancel transactions from previous days.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_PAST_DAY_INVOICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_PAST_DAY_INVOICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void past day invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_PAST_DAY_INVOICE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_PAST_DAY_INVOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to void invoices with used time offers enabling the user to cancel transactions involving redeemed time offers.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void used time invoices.
        /// </summary>
        public static string GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_VOID_USED_TIME_INVOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to make withdrawals enabling the user to deduct funds from customer accounts.
        /// </summary>
        public static string GIZMO_POLICY_SALE_WITHDRAW_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_WITHDRAW_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string GIZMO_POLICY_SALE_WITHDRAW_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SALE_WITHDRAW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        public static string GIZMO_POLICY_SET_CASHIER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SET_CASHIER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string GIZMO_POLICY_SET_MANAGER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SET_MANAGER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketer.
        /// </summary>
        public static string GIZMO_POLICY_SET_MARKETER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SET_MARKETER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string GIZMO_POLICY_SET_OWNER_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SET_OWNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string GIZMO_POLICY_SET_TECHNICIAN_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SET_TECHNICIAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the settings feature enabling the user to view and modify system configurations.
        /// </summary>
        public static string GIZMO_POLICY_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acccess.
        /// </summary>
        public static string GIZMO_POLICY_SETTINGS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SETTINGS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view shift expected amounts enabling the user to review anticipated totals for shifts.
        /// </summary>
        public static string GIZMO_POLICY_SHIFT_COUNT_VIEW_EXPECTED_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SHIFT_COUNT_VIEW_EXPECTED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View expected.
        /// </summary>
        public static string GIZMO_POLICY_SHIFT_COUNT_VIEW_EXPECTED_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_SHIFT_COUNT_VIEW_EXPECTED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the stock feature enabling the user to view and manage inventory items.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manage stock enabling the user to update and control inventory items.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_MANAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_MANAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_MANAGE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_MANAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view past day stock transactions enabling the user to review inventory activities from the previous day.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_VIEW_PAST_DAY_TRANSACTIONS_DESCRIPTIONS {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_VIEW_PAST_DAY_TRANSACTIONS_DESCRIPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View past day transactions.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_VIEW_PAST_DAY_TRANSACTIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_VIEW_PAST_DAY_TRANSACTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view stock transactions enabling the user to review all inventory activities.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_VIEW_TRANSACTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_VIEW_TRANSACTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View transactions.
        /// </summary>
        public static string GIZMO_POLICY_STOCK_VIEW_TRANSACTIONS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_STOCK_VIEW_TRANSACTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to ban users enabling the user to restrict account access for specific users.
        /// </summary>
        public static string GIZMO_POLICY_USER_BAN_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_BAN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban user.
        /// </summary>
        public static string GIZMO_POLICY_USER_BAN_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_BAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to move users to different user groups enabling the user to update user group assignments.
        /// </summary>
        public static string GIZMO_POLICY_USER_CHANGE_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_CHANGE_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change usergroup.
        /// </summary>
        public static string GIZMO_POLICY_USER_CHANGE_GROUP_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_CHANGE_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually create users enabling the user to add new user accounts to the system.
        /// </summary>
        public static string GIZMO_POLICY_USER_CREATE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_CREATE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string GIZMO_POLICY_USER_CREATE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_CREATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to delete users enabling the user to remove user accounts from the system.
        /// </summary>
        public static string GIZMO_POLICY_USER_DELETE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_DELETE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GIZMO_POLICY_USER_DELETE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_DELETE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to edit users personal information enabling the user to update account details.
        /// </summary>
        public static string GIZMO_POLICY_USER_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GIZMO_POLICY_USER_EDIT_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_EDIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to hard delete users enabling the user to permanently remove user accounts from the system.
        /// </summary>
        public static string GIZMO_POLICY_USER_HARD_DELETE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_HARD_DELETE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard delete.
        /// </summary>
        public static string GIZMO_POLICY_USER_HARD_DELETE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_HARD_DELETE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually log in users enabling the user to initiate user sessions directly.
        /// </summary>
        public static string GIZMO_POLICY_USER_MANUAL_LOGIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_MANUAL_LOGIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login users.
        /// </summary>
        public static string GIZMO_POLICY_USER_MANUAL_LOGIN_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_MANUAL_LOGIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually reset user passwords enabling the user to update account credentials.
        /// </summary>
        public static string GIZMO_POLICY_USER_PASSWORD_RESET_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_PASSWORD_RESET_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string GIZMO_POLICY_USER_PASSWORD_RESET_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_PASSWORD_RESET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to rename users enabling the user to update user account names.
        /// </summary>
        public static string GIZMO_POLICY_USER_RENAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_RENAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string GIZMO_POLICY_USER_RENAME_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_RENAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manually unban users enabling the user to restore access for previously banned accounts.
        /// </summary>
        public static string GIZMO_POLICY_USER_UNBAN_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_UNBAN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban user.
        /// </summary>
        public static string GIZMO_POLICY_USER_UNBAN_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_UNBAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to view user stats enabling the user to review activity and performance metrics of users.
        /// </summary>
        public static string GIZMO_POLICY_USER_VIEW_STATS_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_VIEW_STATS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View stats.
        /// </summary>
        public static string GIZMO_POLICY_USER_VIEW_STATS_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_USER_VIEW_STATS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to the waiting lines feature enabling the user to manage and monitor queues.
        /// </summary>
        public static string GIZMO_POLICY_WAITING_LINES_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_WAITING_LINES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants access to manage waiting lines enabling the user to organize and control queue operations.
        /// </summary>
        public static string GIZMO_POLICY_WAITING_LINES_MANAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_WAITING_LINES_MANAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage waiting lines.
        /// </summary>
        public static string GIZMO_POLICY_WAITING_LINES_MANAGE_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_WAITING_LINES_MANAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GIZMO_POLICY_WAITING_LINES_NAME {
            get {
                return ResourceManager.GetString("GIZMO_POLICY_WAITING_LINES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_BOTTOM_CENTER {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_BOTTOM_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_BOTTOM_LEFT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_BOTTOM_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_BOTTOM_RIGHT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_BOTTOM_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Left.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_CENTER_LEFT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_CENTER_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Right.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_CENTER_RIGHT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_CENTER_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Screen.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_CENTER_SCREEN {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_CENTER_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_TOP_CENTER {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_TOP_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_TOP_LEFT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_TOP_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string HOST_NUMBER_FIXED_POSITION_TOP_RIGHT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_FIXED_POSITION_TOP_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_CLOCKWISE {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_CLOCKWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_COUNTERCLOCKWISE {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_COUNTERCLOCKWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_FIXED {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Bottom.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_HORIZONTAL_BOTTOM {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_HORIZONTAL_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Center.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_HORIZONTAL_CENTER {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_HORIZONTAL_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Top.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_HORIZONTAL_TOP {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_HORIZONTAL_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Center.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_VERTICAL_CENTER {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_VERTICAL_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Left.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_VERTICAL_LEFT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_VERTICAL_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Right.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_VERTICAL_RIGHT {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_VERTICAL_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Bounce.
        /// </summary>
        public static string HOST_NUMBER_POSITIONING_WALL_BOUNCE {
            get {
                return ResourceManager.GetString("HOST_NUMBER_POSITIONING_WALL_BOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Signed.
        /// </summary>
        public static string HTTPS_CERTIFICATE_TYPE_SELF_SIGNED {
            get {
                return ResourceManager.GetString("HTTPS_CERTIFICATE_TYPE_SELF_SIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        public static string HTTPS_CERTIFICATE_TYPE_USER_DEFINED {
            get {
                return ResourceManager.GetString("HTTPS_CERTIFICATE_TYPE_USER_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric.
        /// </summary>
        public static string KEY_GENERATION_CHARACTERS_ALPHANUMERIC {
            get {
                return ResourceManager.GetString("KEY_GENERATION_CHARACTERS_ALPHANUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string KEY_GENERATION_CHARACTERS_NUMERIC {
            get {
                return ResourceManager.GetString("KEY_GENERATION_CHARACTERS_NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Case Characters.
        /// </summary>
        public static string KEY_GENERATION_CHARACTERS_UPPER_CASE_CHARACTERS {
            get {
                return ResourceManager.GetString("KEY_GENERATION_CHARACTERS_UPPER_CASE_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string REGISTRATION_VERIFICATION_METHOD_EMAIL_NAME {
            get {
                return ResourceManager.GetString("REGISTRATION_VERIFICATION_METHOD_EMAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string REGISTRATION_VERIFICATION_METHOD_MOBILE_PHONE_NAME {
            get {
                return ResourceManager.GetString("REGISTRATION_VERIFICATION_METHOD_MOBILE_PHONE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string REGISTRATION_VERIFICATION_METHOD_NONE_NAME {
            get {
                return ResourceManager.GetString("REGISTRATION_VERIFICATION_METHOD_NONE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if age restrictions enabled for applications.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_APPLICATIONS_ENABLED_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_APPLICATIONS_ENABLED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable age restrictions for applications.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_APPLICATIONS_ENABLED_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_APPLICATIONS_ENABLED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if age restrictions enabled for login.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_LOGIN_ENABLED_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_LOGIN_ENABLED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable age restrictions for login.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_LOGIN_ENABLED_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_LOGIN_ENABLED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if age restrictions enabled for products.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_PRODUCTS_ENABLED_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_PRODUCTS_ENABLED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable age restrictions for products.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_PRODUCTS_ENABLED_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_PRODUCTS_ENABLED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if age is mandatory for all age restrictions.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_REQUIRE_AGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_REQUIRE_AGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces all restrictions for users with unknown age.
        /// </summary>
        public static string SERVER_OPTION_AGE_RESTRICTIONS_REQUIRE_AGE_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_AGE_RESTRICTIONS_REQUIRE_AGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies remaining time notification message.
        /// </summary>
        public static string SERVER_OPTION_CLIENT_NOTIFICATION_OPTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_CLIENT_NOTIFICATION_OPTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time notification message.
        /// </summary>
        public static string SERVER_OPTION_CLIENT_NOTIFICATION_OPTIONS_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_CLIENT_NOTIFICATION_OPTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies that terminal should be used when paying with credit card.
        /// </summary>
        public static string SERVER_OPTION_PAYMENT_PROCESSING_CREDIT_CARD_USE_TERMINAL_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_PAYMENT_PROCESSING_CREDIT_CARD_USE_TERMINAL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card use terminal.
        /// </summary>
        public static string SERVER_OPTION_PAYMENT_PROCESSING_CREDIT_CARD_USE_TERMINAL_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_PAYMENT_PROCESSING_CREDIT_CARD_USE_TERMINAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies reservation time notification message.
        /// </summary>
        public static string SERVER_OPTION_RESERVATION_NOTIFICATION_OPTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_RESERVATION_NOTIFICATION_OPTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation time notification message.
        /// </summary>
        public static string SERVER_OPTION_RESERVATION_NOTIFICATION_OPTIONS_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_RESERVATION_NOTIFICATION_OPTIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies deposits tax system.
        /// </summary>
        public static string SERVER_OPTION_TAX_DEPOSITS_TAX_SYSTEM_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_TAX_DEPOSITS_TAX_SYSTEM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits tax system.
        /// </summary>
        public static string SERVER_OPTION_TAX_DEPOSITS_TAX_SYSTEM_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_TAX_DEPOSITS_TAX_SYSTEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies goods VAT rate.
        /// </summary>
        public static string SERVER_OPTION_TAX_GOODS_VAT_RATE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_TAX_GOODS_VAT_RATE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods vat rate.
        /// </summary>
        public static string SERVER_OPTION_TAX_GOODS_VAT_RATE_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_TAX_GOODS_VAT_RATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies services VAT rate.
        /// </summary>
        public static string SERVER_OPTION_TAX_SERVICES_VAT_RATE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVER_OPTION_TAX_SERVICES_VAT_RATE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services vat rate.
        /// </summary>
        public static string SERVER_OPTION_TAX_SERVICES_VAT_RATE_NAME {
            get {
                return ResourceManager.GetString("SERVER_OPTION_TAX_SERVICES_VAT_RATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SMTP_SECURITY_NONE_NAME {
            get {
                return ResourceManager.GetString("SMTP_SECURITY_NONE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        public static string SMTP_SECURITY_SSL_NAME {
            get {
                return ResourceManager.GetString("SMTP_SECURITY_SSL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAR TTLS.
        /// </summary>
        public static string SMTP_SECURITY_STARTTLS_NAME {
            get {
                return ResourceManager.GetString("SMTP_SECURITY_STARTTLS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string TAX_SYSTEM_COUNTRY_RUSSIA {
            get {
                return ResourceManager.GetString("TAX_SYSTEM_COUNTRY_RUSSIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string TAX_SYSTEM_COUNTRY_UNSPECIFIED {
            get {
                return ResourceManager.GetString("TAX_SYSTEM_COUNTRY_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_MAIN {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent system.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_PATENT_SYSTEM {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_PATENT_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified system minus expenses.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_EXPSENSES {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_EXPSENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified system minus taxation.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_TAXATION {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_TAXATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single agricultural tax.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_SINGLE_AGRICULTURAL_TAX {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_SINGLE_AGRICULTURAL_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string TAX_SYSTEMS_UNSPECIFIED {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string USER_RECOVERY_METHOD_EMAIL_NAME {
            get {
                return ResourceManager.GetString("USER_RECOVERY_METHOD_EMAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string USER_RECOVERY_METHOD_MOBILE_NAME {
            get {
                return ResourceManager.GetString("USER_RECOVERY_METHOD_MOBILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string USER_RECOVERY_METHOD_NONE_NAME {
            get {
                return ResourceManager.GetString("USER_RECOVERY_METHOD_NONE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string VAT_RATES_RUSSIA_NONE {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT0.
        /// </summary>
        public static string VAT_RATES_RUSSIA_VAT0 {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_VAT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT10.
        /// </summary>
        public static string VAT_RATES_RUSSIA_VAT10 {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_VAT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT20.
        /// </summary>
        public static string VAT_RATES_RUSSIA_VAT20 {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_VAT20", resourceCulture);
            }
        }
    }
}
