using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Payment method type.
    /// </summary>
    /// <remarks>
    /// The enum represent fixed database id's of a known built in methods.
    /// </remarks>
    public enum PaymentMethodType
    {
        /// <summary>
        /// Custom.
        /// </summary>
        [Name("Custom", nameof(Resources.PAYMENT_METHOD_TYPE_CUSTOM_NAME))]
        Custom = 0,

        /// <summary>
        /// Cash payment.
        /// </summary>
        [Name("Cash", nameof(Resources.PAYMENT_METHOD_TYPE_CASH_NAME))]
        Cash = -1,

        /// <summary>
        /// Credit card payment.
        /// </summary>
        [Name("Credit Card", nameof(Resources.PAYMENT_METHOD_TYPE_CREDIT_CARD_NAME))]
        CreditCard = -2,

        /// <summary>
        /// Deposit balance payment.
        /// </summary>
        [Name("Deposit", nameof(Resources.PAYMENT_METHOD_TYPE_DEPOSIT_NAME))]
        Deposit = -3,

        /// <summary>
        /// Points payment.
        /// </summary>
        [Name("Points", nameof(Resources.PAYMENT_METHOD_TYPE_POINTS_NAME))]
        Points = -4,
    }
}
