using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server.Security
{
    /// <summary>
    /// Gizmo policy groups.
    /// </summary>
    public enum GizmoPolicyGroups
    {
        [PolicyGroup(GizmoPolicies.Sale)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SALES_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SALES_DESCRIPTION))]
        Sales,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SHIFT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SHIFT_DESCRIPTION))]
        Shift,

        [PolicyGroup(GizmoPolicies.Stock)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_STOCK_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_STOCK_DESCRIPTION))]
        Stock,

        [PolicyGroup(GizmoPolicies.Monitoring)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_MONITORING_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_STOCK_DESCRIPTION))]
        Monitoring,

        [Obsolete]
        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_DEPLOYMENT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_DEPLOYMENT_DESCRIPTION))]
        Deployment,

        [PolicyGroup(GizmoPolicies.Reports)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_REPORTS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_REPORTS_DESCRIPTION))]
        Reports,

        [PolicyGroup(GizmoPolicies.Settings)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SETTINGS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SETTINGS_DESCRIPTION))]
        Settings,

        [PolicyGroup(GizmoPolicies.Applications)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_APPLICATIONS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_APPLICATIONS_DESCRIPTION))]
        Applications,

        [PolicyGroup(GizmoPolicies.Marketing)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_MARKETING_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_MARKETING_DESCRIPTION))]
        Marketing,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_USER_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_USER_DESCRIPTION))]
        User,

        [PolicyGroup(GizmoPolicies.Log)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_LOG_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_LOG_DESCRIPTION))]
        Log,

        [PolicyGroup(GizmoPolicies.WaitingLines)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_WAITING_LINES_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_WEB_API_DESCRIPTION))]
        WaitingLines,

        [PolicyGroup()]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_REGISTER_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_REGISTER_DESCRIPTION))]
        Register,

        [Obsolete]
        [PolicyGroup(GizmoPolicies.WebApi)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_WEB_API_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_WEB_API_DESCRIPTION))]
        WebApi,

        [PolicyGroup(GizmoPolicies.Management)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_MANAGEMENT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_MANAGEMENT_DESCRIPTION))]
        Management ,

        [PolicyGroup(GizmoPolicies.Reservations)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_RESERVATONS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_RESERVATIONS_DESCRIPTION))]
        Reservations,

        [PolicyGroup(GizmoPolicies.UserGroup)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_USER_GROUP_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_USER_GROUP_DESCRIPTION))]
        UserGroup,

        [PolicyGroup(GizmoPolicies.HostLayout)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_HOST_LAYOUT_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_HOST_LAYOUT_DESCRIPTION))]
        HostLayout,

        [PolicyGroup(GizmoPolicies.Hosts)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_HOSTS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_HOSTS_DESCRIPTION))]
        Hosts,

        [PolicyGroup(GizmoPolicies.HostGroups)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_HOST_GROUPS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_HOST_GROUPS_DESCRIPTION))]
        HostGroups,

        [PolicyGroup(GizmoPolicies.Controllers)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_CONTROLLERS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_CONTROLLERS_DESCRIPTION))]
        Controllers,

        [PolicyGroup(GizmoPolicies.SecurityProfiles)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_SECURITY_PROFILES_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_SECURITY_PROFILES_DESCRIPTION))]
        SecurityProfiles,

        [PolicyGroup(GizmoPolicies.Assets)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_ASSETS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_ASSETS_DESCRIPTION))]
        Assets,

        [PolicyGroup(GizmoPolicies.Tasks)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_TASKS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_TASKS_DESCRIPTION))]
        Tasks,

        [PolicyGroup(GizmoPolicies.ClientTasks)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_CLIENT_TASKS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_CLIENT_TASKS_DESCRIPTION))]
        ClientTasks,

        [PolicyGroup(GizmoPolicies.Products)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_PRODUCTS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_PRODUCTS_DESCRIPTION))]
        Products,

        [PolicyGroup(GizmoPolicies.ProductGroups)]
        [Name("", nameof(Resources.GIZMO_POLICY_GROUP_PRODUCT_GROUPS_NAME))]
        [ExtendedDescription("", nameof(Resources.GIZMO_POLICY_GROUP_PRODUCT_GROUPS_DESCRIPTION))]
        ProductGroups,
    }
}
