using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    public enum DiskSpaceAllocations
    {
        /// <summary>
        /// Zero.
        /// </summary>
        [Name("0%", nameof(Resources.DISK_SPACE_ALLOCATIONS_ZERO))]
        [ExtendedDescription("Zero disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_ZERO_DESCRIPTION))]
        Zero = 0,

        /// <summary>
        /// Five percent.
        /// </summary>
        [Name("5%", nameof(Resources.DISK_SPACE_ALLOCATIONS_FIVE))]
        [ExtendedDescription("5% disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_FIVE_DESCRIPTION))]
        Five = 5,

        /// <summary>
        /// Ten percent.
        /// </summary>
        [Name("10%", nameof(Resources.DISK_SPACE_ALLOCATIONS_TEN))]
        [ExtendedDescription("10% disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_TEN_DESCRIPTION))]
        Ten = 10,

        /// <summary>
        /// Fifteen percent.
        /// </summary>
        [Name("15%", nameof(Resources.DISK_SPACE_ALLOCATIONS_FIFTEEN))]
        [ExtendedDescription("15% disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_FIFTEEN_DESCRIPTION))]
        FifTeen = 15,

        /// <summary>
        /// Twenty percent.
        /// </summary>
        [Name("20%", nameof(Resources.DISK_SPACE_ALLOCATIONS_TWENTY))]
        [ExtendedDescription("20% disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_TWENTY_DESCRIPTION))]
        Twenty = 20,

        /// <summary>
        /// Twenty five percent.
        /// </summary>
        [Name("25%", nameof(Resources.DISK_SPACE_ALLOCATIONS_TWENTY_FIVE))]
        [ExtendedDescription("25% disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_TWENTY_FIVE_DESCRIPTION))]
        TwentyFive = 25,

        /// <summary>
        /// Thirty percent.
        /// </summary>
        [Name("30%", nameof(Resources.DISK_SPACE_ALLOCATIONS_THIRTY))]
        [ExtendedDescription("30% disk space allocation", nameof(Resources.DISK_SPACE_ALLOCATIONS_THIRTY_DESCRIPTION))]
        Thirty = 30
    }
}
