using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    public enum HttpProtocols
    {
        /// <summary>
        /// Http.
        /// </summary>
        [Name("HTTP", nameof(Resources.HTTP_PROTOCOL_HTTP))]
        [ExtendedDescription("HTTP protocol", nameof(Resources.HTTP_PROTOCOL_HTTP_DESCRIPTION))]
        Http = 0,

        /// <summary>
        /// Https.
        /// </summary>
        [Name("HTTPS", nameof(Resources.HTTP_PROTOCOL_HTTPS))]
        [ExtendedDescription("HTTPS protocol", nameof(Resources.HTTP_PROTOCOL_HTTPS_DESCRIPTION))]
        Https = 1,

        /// <summary>
        /// Http and https.
        /// </summary>
        [Name("HTTP and HTTPS", nameof(Resources.HTTP_PROTOCOL_HTTP_HTTPS))]
        [ExtendedDescription("Both HTTP and HTTPS protocols", nameof(Resources.HTTP_PROTOCOL_HTTP_HTTPS_DESCRIPTION))]
        HttpHttps = 2,
    }
}
