using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Https certificate type.
    /// </summary>
    public enum HttpsCertificateType
    {
        /// <summary>
        /// Self signed certificate.
        /// </summary>
        [Name("SelfSigned", nameof(Resources.HTTPS_CERTIFICATE_TYPE_SELF_SIGNED))]
        SelfSigned = 0,

        /// <summary>
        /// User defined certificate.
        /// </summary>
        [Name("UserDefined", nameof(Resources.HTTPS_CERTIFICATE_TYPE_USER_DEFINED))]
        UserDefined = 1,
    }
}
