using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Instance authentication state.
    /// </summary>
    /// <remarks>
    /// This combines previous and current authentication state of the server instance.
    /// </remarks>
    public enum InstanceAuthenticationState
    {
        /// <summary>
        /// Successfully authenticated.
        /// </summary>
        [Name("Success", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_SUCCESS))]
        [ExtendedDescription("Successfully authenticated", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Unauthorized.
        /// </summary>
        [Name("Unauthorized", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_UNAUTHORIZED))]
        [ExtendedDescription("Authentication unauthorized", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_UNAUTHORIZED_DESCRIPTION))]
        Unauthorized = 1,

        /// <summary>
        /// Network error during authentication.
        /// </summary>
        [Name("Network error", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_NETWORK_ERROR))]
        [ExtendedDescription("Network error during authentication", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_NETWORK_ERROR_DESCRIPTION))]
        NetworkError = 2,

        /// <summary>
        /// Error during authentication.
        /// </summary>
        [Name("Error", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_ERROR))]
        [ExtendedDescription("Error during authentication", nameof(Resources.INSTANCE_AUTHENTICATION_STATE_ERROR_DESCRIPTION))]
        Error = 3,
    }
}
