using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Key generation characters.
    /// </summary>
    [Flags()]
    public enum KeyGenerationCharacters
    {
        /// <summary>
        /// Generated keys will contain numbers.
        /// </summary>
        [Name("Numeric", nameof(Resources.KEY_GENERATION_CHARACTERS_NUMERIC))]
        [ExtendedDescription("Generated keys contain numbers only", nameof(Resources.KEY_GENERATION_CHARACTERS_NUMERIC_DESCRIPTION))]
        Numeric = 1,

        /// <summary>
        /// Generated keys will contain upper case characters.
        /// </summary>
        [Name("Upper Case Characters", nameof(Resources.KEY_GENERATION_CHARACTERS_UPPER_CASE_CHARACTERS))]
        [ExtendedDescription("Generated keys contain upper case characters only", nameof(Resources.KEY_GENERATION_CHARACTERS_UPPER_CASE_CHARACTERS_DESCRIPTION))]
        UpperCaseCharacters = 2,

        /// <summary>
        /// Generated keys will contain numbers and upper case characters.
        /// </summary>
        [Name("Alphanumeric", nameof(Resources.KEY_GENERATION_CHARACTERS_ALPHANUMERIC))]
        [ExtendedDescription("Generated keys contain numbers and upper case characters", nameof(Resources.KEY_GENERATION_CHARACTERS_ALPHANUMERIC_DESCRIPTION))]
        Alphanumeric = Numeric | UpperCaseCharacters
    }
}
