using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Registration verification methods.
    /// </summary>
    [Flags()]
    public enum RegistrationVerificationMethod
    {
        /// <summary>
        /// No verification.
        /// </summary>
        [Name("None", nameof(Resources.REGISTRATION_VERIFICATION_METHOD_NONE_NAME))]
        None = 0,

        /// <summary>
        /// Email verification.
        /// </summary>
        [Name("Email", nameof(Resources.REGISTRATION_VERIFICATION_METHOD_EMAIL_NAME))]
        Email = 1,

        /// <summary>
        /// Mobile phone verification.
        /// </summary>
        [Name("Mobile Phone", nameof(Resources.REGISTRATION_VERIFICATION_METHOD_MOBILE_PHONE_NAME))]
        MobilePhone = 2,

        /// <summary>
        /// Messenger verification.
        /// </summary>
        [Name("Messenger", nameof(Resources.REGISTRATION_VERIFICATION_METHOD_MESSENGER_NAME))]
        Messenger = 4,
    }
}
