using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Reservation fee type.
    /// </summary>
    public enum ReservationFeeType
    {
        /// <summary>
        /// None.
        /// </summary>
        [Name("None", nameof(Resources.RESERVATION_FEE_TYPE_NONE))]
        [ExtendedDescription("No reservation fee", nameof(Resources.RESERVATION_FEE_TYPE_NONE_DESCRIPTION))]
        None = 0,

        /// <summary>
        /// Fixed.
        /// </summary>
        [Name("Fixed", nameof(Resources.RESERVATION_FEE_TYPE_FIXED))]
        [ExtendedDescription("Fixed amount reservation fee", nameof(Resources.RESERVATION_FEE_TYPE_FIXED_DESCRIPTION))]
        Fixed = 1,

        /// <summary>
        /// Percentage based.
        /// </summary>
        [Name("Percentage", nameof(Resources.RESERVATION_FEE_TYPE_PERCENTAGE))]
        [ExtendedDescription("Percentage-based reservation fee", nameof(Resources.RESERVATION_FEE_TYPE_PERCENTAGE_DESCRIPTION))]
        Percentage = 2,
    }
}
