using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    public enum SMTPSecurity
    {
        [Name("None", nameof(Resources.SMTP_SECURITY_NONE_NAME))]
        [ExtendedDescription("No encryption", nameof(Resources.SMTP_SECURITY_NONE_DESCRIPTION))]
        None = 0,

        [Name("SSL", nameof(Resources.SMTP_SECURITY_SSL_NAME))]
        [ExtendedDescription("SSL encryption", nameof(Resources.SMTP_SECURITY_SSL_DESCRIPTION))]
        SSL = 1,

        [Name("STARTTLS", nameof(Resources.SMTP_SECURITY_STARTTLS_NAME))]
        [ExtendedDescription("STARTTLS encryption", nameof(Resources.SMTP_SECURITY_STARTTLS_DESCRIPTION))]
        STARTTLS = 2
    }
}
