using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Special folders.
    /// </summary>
    [Flags()]
    public enum SpecialFolders
    {
        /// <summary>
        /// None.
        /// </summary>
        [Name("None", nameof(Resources.SPECIAL_FOLDER_NONE))]
        [ExtendedDescription("No special folder", nameof(Resources.SPECIAL_FOLDER_NONE_DESCRIPTION))]
        None = 0,

        /// <summary>
        /// Desktop flag.
        /// </summary>
        [Name("Desktop", nameof(Resources.SPECIAL_FOLDER_DESKTOP))]
        [ExtendedDescription("Desktop folder", nameof(Resources.SPECIAL_FOLDER_DESKTOP_DESCRIPTION))]
        Desktop = 1,

        /// <summary>
        /// Downloads flag.
        /// </summary>
        [Name("Downloads", nameof(Resources.SPECIAL_FOLDER_DOWNLOADS))]
        [ExtendedDescription("Downloads folder", nameof(Resources.SPECIAL_FOLDER_DOWNLOADS_DESCRIPTION))]
        Downloads = 2,

        /// <summary>
        /// Favorites flag.
        /// </summary>
        [Name("Favorites", nameof(Resources.SPECIAL_FOLDER_FAVORITES))]
        [ExtendedDescription("Favorites folder", nameof(Resources.SPECIAL_FOLDER_FAVORITES_DESCRIPTION))]
        Favorites = 4,

        /// <summary>
        /// My Music flag.
        /// </summary>
        [Name("Music", nameof(Resources.SPECIAL_FOLDER_MUSIC))]
        [ExtendedDescription("Music folder", nameof(Resources.SPECIAL_FOLDER_MUSIC_DESCRIPTION))]
        Music = 8,

        /// <summary>
        /// My pictures flag.
        /// </summary>
        [Name("Pictures", nameof(Resources.SPECIAL_FOLDER_PICTURES))]
        [ExtendedDescription("Pictures folder", nameof(Resources.SPECIAL_FOLDER_PICTURES_DESCRIPTION))]
        Pictures = 16,

        /// <summary>
        /// My videos flag.
        /// </summary>
        [Name("Videos", nameof(Resources.SPECIAL_FOLDER_VIDEOS))]
        [ExtendedDescription("Videos folder", nameof(Resources.SPECIAL_FOLDER_VIDEOS_DESCRIPTION))]
        Videos = 32,

        /// <summary>
        /// Saved games flag.
        /// </summary>
        [Name("Saved Games", nameof(Resources.SPECIAL_FOLDER_SAVED_GAMES))]
        [ExtendedDescription("Saved games folder", nameof(Resources.SPECIAL_FOLDER_SAVED_GAMES_DESCRIPTION))]
        SavedGames = 64,

        /// <summary>
        /// Personal flag (Equals MyDocuments).
        /// </summary>
        [Name("Personal", nameof(Resources.SPECIAL_FOLDER_PERSONAL))]
        [ExtendedDescription("Personal documents folder", nameof(Resources.SPECIAL_FOLDER_PERSONAL_DESCRIPTION))]
        Personal = 128,
    }
}
