using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    [Flags()]
    public enum UserRoles
    {
        /// <summary>
        /// No role.
        /// </summary>
        [Name("None", nameof(Resources.USER_ROLE_NONE))]
        [ExtendedDescription("No role assigned", nameof(Resources.USER_ROLE_NONE_DESCRIPTION))]
        None = 0,

        /// <summary>
        /// Simple user.
        /// </summary>
        [Name("User", nameof(Resources.USER_ROLE_USER))]
        [ExtendedDescription("Standard user role", nameof(Resources.USER_ROLE_USER_DESCRIPTION))]
        User = 1,

        /// <summary>
        /// Guest user role.
        /// </summary>
        [Name("Guest", nameof(Resources.USER_ROLE_GUEST))]
        [ExtendedDescription("Guest user role", nameof(Resources.USER_ROLE_GUEST_DESCRIPTION))]
        Guest = 2,

        /// <summary>
        /// Operator.
        /// </summary>
        [Name("Operator", nameof(Resources.USER_ROLE_OPERATOR))]
        [ExtendedDescription("Operator role", nameof(Resources.USER_ROLE_OPERATOR_DESCRIPTION))]
        Operator = 4
    }
}
