using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// Recovery method.
    /// </summary>
    /// <remarks>
    /// This enum is used to provide available user (password,username e.t.c) recovery methods information.
    /// </remarks>
    [Flags()]
    public enum UserRecoveryMethod
    {
        /// <summary>
        /// No recovery method.
        /// </summary>
        [Name("None", nameof(Resources.USER_RECOVERY_METHOD_NONE_NAME))]
        [ExtendedDescription("No recovery method available", nameof(Resources.USER_RECOVERY_METHOD_NONE_DESCRIPTION))]
        None = 0,

        /// <summary>
        /// Recovery by mobile phone.
        /// </summary>
        [Name("Mobile", nameof(Resources.USER_RECOVERY_METHOD_MOBILE_NAME))]
        [ExtendedDescription("Recovery via mobile phone", nameof(Resources.USER_RECOVERY_METHOD_MOBILE_DESCRIPTION))]
        Mobile = 1,

        /// <summary>
        /// Recovery by email.
        /// </summary>
        [Name("Email", nameof(Resources.USER_RECOVERY_METHOD_EMAIL_NAME))]
        [ExtendedDescription("Recovery via email", nameof(Resources.USER_RECOVERY_METHOD_EMAIL_DESCRIPTION))]
        Email = 2,
    }
}
