using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo.Server
{
    /// <summary>
    /// User search field types.
    /// </summary>
    public enum UserSearchFieldType
    {
        [Name("Mobile phone", nameof(Resources.USER_SEARCH_FIELD_TYPE_MOBILE_PHONE))]
        [ExtendedDescription("Search by mobile phone number", nameof(Resources.USER_SEARCH_FIELD_TYPE_MOBILE_PHONE_DESCRIPTION))]
        MobilePhone = 0,

        [Name("Username", nameof(Resources.USER_SEARCH_FIELD_TYPE_USERNAME))]
        [ExtendedDescription("Search by username", nameof(Resources.USER_SEARCH_FIELD_TYPE_USERNAME_DESCRIPTION))]
        Username = 1,

        [Name("Email", nameof(Resources.USER_SEARCH_FIELD_TYPE_EMAIL))]
        [ExtendedDescription("Search by email address", nameof(Resources.USER_SEARCH_FIELD_TYPE_EMAIL_DESCRIPTION))]
        Email = 2,

        [Name("Identification number", nameof(Resources.USER_SEARCH_FIELD_TYPE_IDENTIFICATION_NUMBER))]
        [ExtendedDescription("Search by identification number", nameof(Resources.USER_SEARCH_FIELD_TYPE_IDENTIFICATION_NUMBER_DESCRIPTION))]
        IdentificationNumber = 3,

        [Name("First name", nameof(Resources.USER_SEARCH_FIELD_TYPE_FIRST_NAME))]
        [ExtendedDescription("Search by first name", nameof(Resources.USER_SEARCH_FIELD_TYPE_FIRST_NAME_DESCRIPTION))]
        FirstName = 4,

        [Name("Last name", nameof(Resources.USER_SEARCH_FIELD_TYPE_LAST_NAME))]
        [ExtendedDescription("Search by last name", nameof(Resources.USER_SEARCH_FIELD_TYPE_LAST_NAME_DESCRIPTION))]
        LastName = 5,

        [Name("Attributes", nameof(Resources.USER_SEARCH_FIELD_TYPE_ATTRIBUTES))]
        [ExtendedDescription("Search by attributes", nameof(Resources.USER_SEARCH_FIELD_TYPE_ATTRIBUTES_DESCRIPTION))]
        Attributes = 6,

        [Name("Phone", nameof(Resources.USER_SEARCH_FIELD_TYPE_PHONE))]
        [ExtendedDescription("Search by phone number", nameof(Resources.USER_SEARCH_FIELD_TYPE_PHONE_DESCRIPTION))]
        Phone = 7,

        [Name("User group", nameof(Resources.USER_SEARCH_FIELD_TYPE_USER_GROUP))]
        [ExtendedDescription("Search by user group", nameof(Resources.USER_SEARCH_FIELD_TYPE_USER_GROUP_DESCRIPTION))]
        UserGroup = 8,
    }
}
