using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Advance payment types.
    /// </summary>
    /// <remarks>
    /// In payment system this describes the prepayment/advance payments and similar.
    /// </remarks>
    public enum AdvancePaymentTypes
    {
        /// <summary>
        /// Full prepayment (full_prepayment).
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Full prepayment", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_FULL_PREPAYMENT))]
        [ExtendedDescription("Full prepayment before delivery of goods or services", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_FULL_PREPAYMENT_DESCRIPTION))]
        RU_full_prepayment = 0,

        /// <summary>
        /// Prepayment (prepayment).
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Prepayment", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_PREPAYMENT))]
        [ExtendedDescription("Partial prepayment before delivery of goods or services", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_PREPAYMENT_DESCRIPTION))]
        RU_prepayment = 1,

        /// <summary>
        /// Advance (advance).
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Advance", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_ADVANCE))]
        [ExtendedDescription("Advance payment for goods or services", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_ADVANCE_DESCRIPTION))]
        RU_advance = 2,

        /// <summary>
        /// Full payment (full_payment).
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Full payment", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_FULL_PAYMENT))]
        [ExtendedDescription("Full payment at the time of delivery", nameof(Resources.ADVANCE_PAYMENTS_RUSSIA_FULL_PAYMENT_DESCRIPTION))]
        RU_full_payment = 3,
    }
}
