using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Line type.
    /// </summary>
    public enum LineType
    {
        [Name("Product", nameof(Resources.LINE_TYPE_PRODUCT))]
        [ExtendedDescription("Product line item", nameof(Resources.LINE_TYPE_PRODUCT_DESCRIPTION))]
        Product = 0,

        [Name("Time product", nameof(Resources.LINE_TYPE_TIME_PRODUCT))]
        [ExtendedDescription("Time-based product line item", nameof(Resources.LINE_TYPE_TIME_PRODUCT_DESCRIPTION))]
        TimeProduct = 1,

        [Name("Fixed time", nameof(Resources.LINE_TYPE_FIXED_TIME))]
        [ExtendedDescription("Fixed time line item", nameof(Resources.LINE_TYPE_FIXED_TIME_DESCRIPTION))]
        FixedTime = 2,

        [Name("Session time", nameof(Resources.LINE_TYPE_SESSION_TIME))]
        [ExtendedDescription("Session time line item", nameof(Resources.LINE_TYPE_SESSION_TIME_DESCRIPTION))]
        SessionTime = 3,

        [Name("Deposit", nameof(Resources.LINE_TYPE_DEPOSIT))]
        [ExtendedDescription("Deposit line item", nameof(Resources.LINE_TYPE_DEPOSIT_DESCRIPTION))]
        Deposit = 4,

        [Name("Reservation fee", nameof(Resources.LINE_TYPE_RESERVATION_FEE))]
        [ExtendedDescription("Reservation fee line item", nameof(Resources.LINE_TYPE_RESERVATION_FEE_DESCRIPTION))]
        ReservationFee = 5,
    }
}
