using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Tax systems.
    /// </summary>
    public enum TaxSystems
    {
        /// <summary>
        /// Undefined.
        /// </summary>
        /// <remarks>
        /// Had to keep this enum in order to preserve compatibility with existing configuration.
        /// </remarks>
        [Name("Undefined", nameof(Resources.TAX_SYSTEMS_UNDEFINED))]
        [ExtendedDescription("Undefined tax system", nameof(Resources.TAX_SYSTEMS_UNDEFINED_DESCRIPTION))]
        Undefined = 0,

        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Main", nameof(Resources.TAX_SYSTEMS_RUSSIA_MAIN))]
        [ExtendedDescription("Main taxation system", nameof(Resources.TAX_SYSTEMS_RUSSIA_MAIN_DESCRIPTION))]
        RU_Main = 1,

        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Simplified system minus taxation", nameof(Resources.TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_TAXATION))]
        [ExtendedDescription("Simplified taxation system based on income", nameof(Resources.TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_TAXATION_DESCRIPTION))]
        RU_SimplifiedSystemIncomeTaxation = 2,

        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Simplified system minus expenses", nameof(Resources.TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_EXPSENSES))]
        [ExtendedDescription("Simplified taxation system based on income minus expenses", nameof(Resources.TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_EXPSENSES_DESCRIPTION))]
        RU_SimplifiedSystemIncomeMinusExpenses = 3,

        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Single agricultural tax", nameof(Resources.TAX_SYSTEMS_RUSSIA_SINGLE_AGRICULTURAL_TAX))]
        [ExtendedDescription("Single tax for agricultural producers", nameof(Resources.TAX_SYSTEMS_RUSSIA_SINGLE_AGRICULTURAL_TAX_DESCRIPTION))]
        RU_SingleAgriculturalTax = 4,

        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("Patent system", nameof(Resources.TAX_SYSTEMS_RUSSIA_PATENT_SYSTEM))]
        [ExtendedDescription("Patent-based taxation system", nameof(Resources.TAX_SYSTEMS_RUSSIA_PATENT_SYSTEM_DESCRIPTION))]
        RU_PatentSystem = 5
    }
}
