using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Tax system country.
    /// </summary>
    /// <remarks>
    /// Used to group tax systems <see cref="TaxSystems"/> by country.
    /// </remarks>
    public enum TaxSystemCountry
    {
        /// <summary>
        /// None.
        /// </summary>
        [Name("Unspecified", nameof(Resources.TAX_SYSTEM_COUNTRY_UNSPECIFIED))]
        [ExtendedDescription("No specific country tax system", nameof(Resources.TAX_SYSTEM_COUNTRY_UNSPECIFIED_DESCRIPTION))]
        None = 0,

        /// <summary>
        /// Russia.
        /// </summary>
        [Name("Russia", nameof(Resources.TAX_SYSTEM_COUNTRY_RUSSIA))]
        [ExtendedDescription("Russian Federation tax system", nameof(Resources.TAX_SYSTEM_COUNTRY_RUSSIA_DESCRIPTION))]
        Russia = 1,
    }
}
