using System.ComponentModel.DataAnnotations;
using Gizmo.Shared.Resources.Autogenerated;

namespace Gizmo
{
    /// <summary>
    /// Global VAT rates enumeration.
    /// </summary>
    public enum VatRates
    {
        /// <summary>
        /// None (none)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("None", nameof(Resources.VAT_RATES_RUSSIA_NONE))]
        [ExtendedDescription("No VAT applied", nameof(Resources.VAT_RATES_RUSSIA_NONE_DESCRIPTION))]
        RU_none = 0,

        /// <summary>
        /// Zero VAT (vat0)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT0", nameof(Resources.VAT_RATES_RUSSIA_VAT0))]
        [ExtendedDescription("Zero percent VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT0_DESCRIPTION))]
        RU_vat0 = 1,

        /// <summary>
        /// 10% VAT (vat10)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT10", nameof(Resources.VAT_RATES_RUSSIA_VAT10))]
        [ExtendedDescription("10% VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT10_DESCRIPTION))]
        RU_vat10 = 2,

        /// <summary>
        /// 20% VAT (vat20)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT20", nameof(Resources.VAT_RATES_RUSSIA_VAT20))]
        [ExtendedDescription("20% VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT20_DESCRIPTION))]
        RU_vat20 = 3,

        /// <summary>
        /// 5% VAT (vat5)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT5", nameof(Resources.VAT_RATES_RUSSIA_VAT5))]
        [ExtendedDescription("5% VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT5_DESCRIPTION))]
        RU_vat5 = 4,

        /// <summary>
        /// 7% VAT (vat7)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT7", nameof(Resources.VAT_RATES_RUSSIA_VAT7))]
        [ExtendedDescription("7% VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT7_DESCRIPTION))]
        RU_vat7 = 5,

        /// <summary>
        /// 5/105% VAT (vat105)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT105", nameof(Resources.VAT_RATES_RUSSIA_VAT105))]
        [ExtendedDescription("5/105% calculated VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT105_DESCRIPTION))]
        RU_vat105 = 6,

        /// <summary>
        /// 7/107% VAT (vat107)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT107", nameof(Resources.VAT_RATES_RUSSIA_VAT107))]
        [ExtendedDescription("7/107% calculated VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT107_DESCRIPTION))]
        RU_vat107 = 7,

        /// <summary>
        /// 10/110% VAT (vat110)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT110", nameof(Resources.VAT_RATES_RUSSIA_VAT110))]
        [ExtendedDescription("10/110% calculated VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT110_DESCRIPTION))]
        RU_vat110 = 8,

        /// <summary>
        /// 20/120% VAT (vat120)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT120", nameof(Resources.VAT_RATES_RUSSIA_VAT120))]
        [ExtendedDescription("20/120% calculated VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT120_DESCRIPTION))]
        RU_vat120 = 9,

        /// <summary>
        /// 22% VAT (vat22)
        /// </summary>
        [TaxSystemCountry(TaxSystemCountry.Russia)]
        [Name("VAT22", nameof(Resources.VAT_RATES_RUSSIA_VAT22))]
        [ExtendedDescription("22% VAT rate", nameof(Resources.VAT_RATES_RUSSIA_VAT22_DESCRIPTION))]
        RU_vat22 = 10,
    }
}
